Update for export to github.com from mamba.ru

diff --git a/.github/workflows/mambaru.yml b/.github/workflows/mambaru.yml
--- a/.github/workflows/mambaru.yml
+++ b/.github/workflows/mambaru.yml
@@ -13,12 +13,8 @@ jobs:
 
       - name: Install packages
         run: |
-          sudo locale-gen ru_RU
-          sudo locale-gen ru_RU.UTF-8
-          sudo update-locale
-
-          sudo apt-get install -y lcov
-          ./boost-setup.sh
+          export GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
+          bash setup.sh
         working-directory: ./.github/workflows
 
       - name: Coverage report and push to master branches
@@ -26,14 +22,14 @@ jobs:
           echo "Субмодули подключаються при первой сборке (фиксируем их)"
           git config --global user.email "migashko@gmail.com"
           git config --global user.name "Vladimir Migashko"
+          git config pull.rebase true
           git pull origin master
-          make init
+          make coverage-report
           git add .
           git commit -am "[subm] build submodule autocommit" || true
           pushd build
              export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
-             bash <(curl -s https://codecov.io/bash)
+             bash <(curl -s https://codecov.io/bash) || echo "Coverage FAIL!"
           popd
           git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git HEAD:master
-          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git :mamba-ready || true
           git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git :mambaru || echo "Delete mambaru FAIL"
